In [4]:
print("Hello World")

Hello World


In [5]:
import tensorflow_hub as hub


In [6]:
import tensorflow_text as text

In [7]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"


In [8]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [97]:
text_test = ['I am Dev','I am Dev']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [98]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  1045,  2572, 16475,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [99]:
bert_model = hub.KerasLayer(encoder_url)

In [100]:
bert_results = bert_model(text_preprocessed)

In [101]:
bert_results.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [102]:
bert_results['sed_output']



<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.01838351,  0.38482517,  0.06968008, ..., -0.09037483,
          0.1662078 ,  0.13959771],
        [ 0.20669919,  0.28990418,  0.28494158, ..., -0.17058128,
          0.74460214,  0.24932578],
        [-0.01929044, -0.13073239,  0.10871704, ...,  0.13989496,
          0.8067612 ,  0.14132564],
        ...,
        [ 0.34129933, -0.04352018,  0.43873808, ...,  0.03300644,
         -0.00254342,  0.0122118 ],
        [ 0.342381  , -0.10944676,  0.35078356, ...,  0.06117718,
         -0.06392184, -0.02041232],
        [ 0.15711905, -0.20284602,  0.32967615, ...,  0.16531467,
         -0.12976128, -0.16543707]],

       [[ 0.01838351,  0.38482517,  0.06968008, ..., -0.09037483,
          0.1662078 ,  0.13959771],
        [ 0.20669919,  0.28990418,  0.28494158, ..., -0.17058128,
          0.74460214,  0.24932578],
        [-0.01929044, -0.13073239,  0.10871704, ...,  0.13989496,
          0.8067612 ,  0.14132564],
        ...,

In [103]:
# Extract important keywords (manual filtering for this example)
def filter_keywords(tokens):
    # Assuming "zoom" and any proper nouns (like "delhi") are important
    return [token for token in tokens if token in ["zoom", "delhi"]]

# Filter tokens for keywords
important_keywords1 = filter_keywords(keywords1)
important_keywords2 = filter_keywords(keywords2)

print(important_keywords1)  # ["zoom", "delhi"]
print(important_keywords2)  # ["zoom", "delhi"]

NameError: name 'keywords1' is not defined